In [19]:
import pandas as pd

In [20]:
df=pd.read_csv("StudentsPerformance.csv")

In [21]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [22]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [23]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [24]:
df.shape

(1000, 8)

In [30]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [31]:
df.info

<bound method DataFrame.info of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>

In [32]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [43]:
categorical_cols=["gender","race/ethnicity","parental level of education","lunch","test preparation course"]	
for cols in categorical_cols:
    df[cols]=df[cols].astype(str).str.strip().str.lower()

In [44]:
df[cols]

0           none
1      completed
2           none
3           none
4           none
         ...
995    completed
996         none
997    completed
998    completed
999         none
Name: test preparation course, Length: 1000, dtype: object

In [45]:
score_cols=["math score","reading score","writing score"]	
for cols in score_cols:
    mean=df[cols].mean()
    median=df[cols].median()
    mode=df[cols].mode()
    std=df[cols].std()
    var=df[cols].var()
    quantile1=df[cols].quantile(0.25)
    quantile3=df[cols].quantile(0.75)
    print("mean score:",mean)
    print("median score:",median)
    print("mode score:",mode)
    print("standard deviation score:",std)
    print("variance score:",var)
    print("Q1 score:",quantile1)
    print("Q3 score:",quantile3)

mean score: 66.089
median score: 66.0
mode score: 0    65
Name: math score, dtype: int64
standard deviation score: 15.163080096009468
variance score: 229.91899799799847
Q1 score: 57.0
Q3 score: 77.0
mean score: 69.169
median score: 70.0
mode score: 0    72
Name: reading score, dtype: int64
standard deviation score: 14.60019193725222
variance score: 213.1656046046047
Q1 score: 59.0
Q3 score: 79.0
mean score: 68.054
median score: 69.0
mode score: 0    74
Name: writing score, dtype: int64
standard deviation score: 15.195657010869642
variance score: 230.90799199199168
Q1 score: 57.75
Q3 score: 79.0

In [47]:
score_cols = ["math score", "reading score", "writing score"]

print(df[score_cols].describe())

df["total marks"] = df[score_cols].sum(axis=1)

df["percentage"] = (df["total marks"] / 300) * 100

print(df[score_cols + ["total marks", "percentage"]])

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000
     math score  reading score  writing score  total marks  percentage
0            72             72             74          218   72.666667
1            69             90             88          247   82.333333
2            90             95             93          278   92.666667
3            47             57             44          148   49.333333
4            76             78             75          229   76.333333
..          ...            ...            ...          ...         ...
995          88             99             95          282   94.000000
996          62             55             55          172   57.333333
997          59             71             65          195   65.000000
998          68             78             77          223   74.333333
999          77             86             86          249   83.000000

[1000 rows x 5 columns]

In [51]:
performance=[]
for percentage in df["percentage"]:
    if percentage>=90:
        performance.append("Excellent")
    elif  percentage>=75:
        performance.append("Very good")
    elif  percentage>=60:
         performance.append("good")
    elif  percentage>=50:
        performance.append("Average")
    else:
        performance.append("need improvement")
df["Performance"]=performance
print(df[["percentage","Performance"]])

     percentage       Performance
0     72.666667              good
1     82.333333         Very good
2     92.666667         Excellent
3     49.333333  need improvement
4     76.333333         Very good
..          ...               ...
995   94.000000         Excellent
996   57.333333           Average
997   65.000000              good
998   74.333333              good
999   83.000000         Very good

[1000 rows x 2 columns]

In [52]:
for col in ["math score","reading score","writing score"]:
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)

    IQR=Q3-Q1
    lower=Q1-1.5*IQR
    upper=Q3+1.5*IQR

    outliers=df[
        (df[col]<lower) |
        (df[col]>upper)
        ]
    print(outliers[col])

17     18
59      0
145    22
338    24
466    26
787    19
842    23
980     8
Name: math score, dtype: int64
59     17
76     26
211    28
327    23
596    24
980    24
Name: reading score, dtype: int64
59     10
76     22
327    19
596    15
980    23
Name: writing score, dtype: int64