In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("stock_data_50_records.csv")

In [6]:
df

          Date    Open    High     Low   Close    Volume
0   2026-01-02  101.09  103.37  100.08  102.04   89377.0
1   2026-01-05  101.05  101.99   99.91  100.58   88404.0
2   2026-01-06  102.41  103.15   99.47  101.36   94045.0
3   2026-01-07  105.35  108.05  103.53  106.87   72352.0
4   2026-01-08  105.13  109.88  104.24  107.49   79790.0
5   2026-01-09  104.91  108.22  103.42  107.07   81919.0
6   2026-01-12  107.95  109.49  104.84  106.57   45600.0
7   2026-01-13  109.53  111.44  107.88     NaN   69124.0
8   2026-01-14  108.89  111.08  107.60  109.85   67643.0
9   2026-01-15  110.07  114.76  109.21  112.32   80764.0
10  2026-01-16  109.43  111.85  108.13  108.77   49007.0
11  2026-01-19  108.79  109.79  106.87  108.72  450000.0
12  2026-01-20  109.43  110.92  105.67  107.52   96835.0
13  2026-01-21  106.18  107.28  102.64  104.09   77410.0
14  2026-01-22  103.28  106.28  102.27  105.21   84080.0
15  2026-01-23  102.47  106.05  101.45  105.48   80447.0
16  2026-01-26  100.84  102.72   99.25  101.00   48208.0
17  2026-01-27  101.61  105.43   99.76  103.92   96491.0
18  2026-01-28  100.18  101.80   98.35  101.20       NaN
19  2026-01-29   97.83   98.89   95.17   96.84   58589.0
20  2026-01-09  104.91  108.22  103.42  107.07   81919.0
21  2026-02-02  100.47  104.83   99.84  103.85   57453.0
22  2026-02-03  100.79  101.81  100.05  101.02   76212.0
23  2026-02-04   98.42  103.33   96.57  101.85   83525.0
24  2026-02-05   97.64  100.11   91.29   92.70   87202.0
25  2026-02-06   98.04  100.96   97.53   99.98   72635.0
26  2026-02-09   96.17   98.48   95.52   96.64   73828.0
27  2026-02-10   97.05   99.07   95.25   96.75  620000.0
28  2026-02-11   96.17   97.63   95.66   96.65   43420.0
29  2026-02-12   95.84   97.80   91.42   92.16   71216.0
30  2026-02-13   94.96   96.20   93.50   94.82   40301.0
31  2026-02-16   98.49  101.26   96.95   99.50   85236.0
32  2026-02-17   98.67     NaN   97.19  101.93   89758.0
33  2026-02-18   96.96   98.53   95.38   96.22   92322.0
34  2026-02-19   98.64   99.32   95.75   97.32   40699.0
35  2026-01-22  103.28  106.28  102.27  105.21   84080.0
36  2026-02-23   97.22  100.49   96.23   99.35   98483.0
37  2026-02-24   93.89   95.72   92.27   94.85   40190.0
38  2026-02-25   91.70   92.28   89.47   90.94   50492.0
39  2026-02-26   92.26   95.27   90.49   93.59   90132.0
40  2026-02-27   93.79   96.14   92.30   94.28   75743.0
41  2026-03-02   94.30   97.07   92.95   96.54  850000.0
42  2026-03-03   94.29   95.81   92.55   93.19   90336.0
43  2026-03-04   93.95   94.90   92.54   93.59   92479.0
44  2026-03-05     NaN   93.27   90.10   91.00   59778.0
45  2026-03-06   90.39   91.24   86.89   87.76   97471.0
46  2026-03-09   89.76   92.53   87.80   90.65   66641.0
47  2026-02-06   98.04  100.96   97.53   99.98   72635.0
48  2026-03-11   92.68   95.36   90.84   92.99   72745.0
49  2026-03-12   89.71   90.49   88.09   89.54   95006.0

In [7]:
df.tail()

          Date   Open    High    Low  Close   Volume
45  2026-03-06  90.39   91.24  86.89  87.76  97471.0
46  2026-03-09  89.76   92.53  87.80  90.65  66641.0
47  2026-02-06  98.04  100.96  97.53  99.98  72635.0
48  2026-03-11  92.68   95.36  90.84  92.99  72745.0
49  2026-03-12  89.71   90.49  88.09  89.54  95006.0

In [8]:
df.head()

         Date    Open    High     Low   Close   Volume
0  2026-01-02  101.09  103.37  100.08  102.04  89377.0
1  2026-01-05  101.05  101.99   99.91  100.58  88404.0
2  2026-01-06  102.41  103.15   99.47  101.36  94045.0
3  2026-01-07  105.35  108.05  103.53  106.87  72352.0
4  2026-01-08  105.13  109.88  104.24  107.49  79790.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Open    49 non-null     float64
 2   High    49 non-null     float64
 3   Low     50 non-null     float64
 4   Close   49 non-null     float64
 5   Volume  49 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.5+ KB

In [10]:
df["Date"] = pd.to_datetime(df["Date"])
df.dtypes

Date      datetime64[ns]
Open             float64
High             float64
Low              float64
Close            float64
Volume           float64
dtype: object

In [11]:
df.isnull().sum()

Date      0
Open      1
High      1
Low       0
Close     1
Volume    1
dtype: int64

In [12]:
df=df.dropna()

In [13]:
df

         Date    Open    High     Low   Close    Volume
0  2026-01-02  101.09  103.37  100.08  102.04   89377.0
1  2026-01-05  101.05  101.99   99.91  100.58   88404.0
2  2026-01-06  102.41  103.15   99.47  101.36   94045.0
3  2026-01-07  105.35  108.05  103.53  106.87   72352.0
4  2026-01-08  105.13  109.88  104.24  107.49   79790.0
5  2026-01-09  104.91  108.22  103.42  107.07   81919.0
6  2026-01-12  107.95  109.49  104.84  106.57   45600.0
8  2026-01-14  108.89  111.08  107.60  109.85   67643.0
9  2026-01-15  110.07  114.76  109.21  112.32   80764.0
10 2026-01-16  109.43  111.85  108.13  108.77   49007.0
11 2026-01-19  108.79  109.79  106.87  108.72  450000.0
12 2026-01-20  109.43  110.92  105.67  107.52   96835.0
13 2026-01-21  106.18  107.28  102.64  104.09   77410.0
14 2026-01-22  103.28  106.28  102.27  105.21   84080.0
15 2026-01-23  102.47  106.05  101.45  105.48   80447.0
16 2026-01-26  100.84  102.72   99.25  101.00   48208.0
17 2026-01-27  101.61  105.43   99.76  103.92   96491.0
19 2026-01-29   97.83   98.89   95.17   96.84   58589.0
20 2026-01-09  104.91  108.22  103.42  107.07   81919.0
21 2026-02-02  100.47  104.83   99.84  103.85   57453.0
22 2026-02-03  100.79  101.81  100.05  101.02   76212.0
23 2026-02-04   98.42  103.33   96.57  101.85   83525.0
24 2026-02-05   97.64  100.11   91.29   92.70   87202.0
25 2026-02-06   98.04  100.96   97.53   99.98   72635.0
26 2026-02-09   96.17   98.48   95.52   96.64   73828.0
27 2026-02-10   97.05   99.07   95.25   96.75  620000.0
28 2026-02-11   96.17   97.63   95.66   96.65   43420.0
29 2026-02-12   95.84   97.80   91.42   92.16   71216.0
30 2026-02-13   94.96   96.20   93.50   94.82   40301.0
31 2026-02-16   98.49  101.26   96.95   99.50   85236.0
33 2026-02-18   96.96   98.53   95.38   96.22   92322.0
34 2026-02-19   98.64   99.32   95.75   97.32   40699.0
35 2026-01-22  103.28  106.28  102.27  105.21   84080.0
36 2026-02-23   97.22  100.49   96.23   99.35   98483.0
37 2026-02-24   93.89   95.72   92.27   94.85   40190.0
38 2026-02-25   91.70   92.28   89.47   90.94   50492.0
39 2026-02-26   92.26   95.27   90.49   93.59   90132.0
40 2026-02-27   93.79   96.14   92.30   94.28   75743.0
41 2026-03-02   94.30   97.07   92.95   96.54  850000.0
42 2026-03-03   94.29   95.81   92.55   93.19   90336.0
43 2026-03-04   93.95   94.90   92.54   93.59   92479.0
45 2026-03-06   90.39   91.24   86.89   87.76   97471.0
46 2026-03-09   89.76   92.53   87.80   90.65   66641.0
47 2026-02-06   98.04  100.96   97.53   99.98   72635.0
48 2026-03-11   92.68   95.36   90.84   92.99   72745.0
49 2026-03-12   89.71   90.49   88.09   89.54   95006.0

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df=df.drop_duplicates()

In [41]:
df.duplicated().sum()

np.int64(0)

In [26]:
df["Price_Delta"] = df["Close"] - df["Open"]
df

C:\Users\HP\AppData\Local\Temp\ipykernel_18856\4257002924.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price_Delta"] = df["Close"] - df["Open"]

,Date,Open,High,Low,Close,Volume,Volume_MA_7,Price_Delta
0,2026-01-02,101.09,103.37,100.08,102.04,89377.0,NaN,0.95
1,2026-01-05,101.05,101.99,99.91,100.58,88404.0,NaN,-0.47
2,2026-01-06,102.41,103.15,99.47,101.36,94045.0,NaN,-1.05
3,2026-01-07,105.35,108.05,103.53,106.87,72352.0,NaN,1.52
4,2026-01-08,105.13,109.88,104.24,107.49,79790.0,NaN,2.36
5,2026-01-09,104.91,108.22,103.42,107.07,81919.0,NaN,2.16
6,2026-01-12,107.95,109.49,104.84,106.57,45600.0,78783.857143,-1.38
8,2026-01-14,108.89,111.08,107.60,109.85,67643.0,75679.000000,0.96
9,2026-01-15,110.07,114.76,109.21,112.32,80764.0,74587.571429,2.25
10,2026-01-16,109.43,111.85,108.13,108.77,49007.0,68153.571429,-0.66
11,2026-01-19,108.79,109.79,106.87,108.72,450000.0,122103.285714,-0.07
12,2026-01-20,109.43,110.92,105.67,107.52,96835.0,124538.285714,-1.91
13,2026-01-21,106.18,107.28,102.64,104.09,77410.0,123894.142857,-2.09
14,2026-01-22,103.28,106.28,102.27,105.21,84080.0,129391.285714,1.93
15,2026-01-23,102.47,106.05,101.45,105.48,80447.0,131220.428571,3.01
16,2026-01-26,100.84,102.72,99.25,101.00,48208.0,126569.571429,0.16
17,2026-01-27,101.61,105.43,99.76,103.92,96491.0,133353.000000,2.31
19,2026-01-29,97.83,98.89,95.17,96.84,58589.0,77437.142857,-0.99
20,2026-01-09,104.91,108.22,103.42,107.07,81919.0,75306.285714,2.16
21,2026-02-02,100.47,104.83,99.84,103.85,57453.0,72455.285714,3.38
22,2026-02-03,100.79,101.81,100.05,101.02,76212.0,71331.285714,0.23
23,2026-02-04,98.42,103.33,96.57,101.85,83525.0,71771.000000,3.43
24,2026-02-05,97.64,100.11,91.29,92.70,87202.0,77341.571429,-4.94
25,2026-02-06,98.04,100.96,97.53,99.98,72635.0,73933.571429,1.94
26,2026-02-09,96.17,98.48,95.52,96.64,73828.0,76110.571429,0.47
27,2026-02-10,97.05,99.07,95.25,96.75,620000.0,152979.285714,-0.30
28,2026-02-11,96.17,97.63,95.66,96.65,43420.0,150974.571429,0.48
29,2026-02-12,95.84,97.80,91.42,92.16,71216.0,150260.857143,-3.68
30,2026-02-13,94.96,96.20,93.50,94.82,40301.0,144086.000000,-0.14
31,2026-02-16,98.49,101.26,96.95,99.50,85236.0,143805.142857,1.01
33,2026-02-18,96.96,98.53,95.38,96.22,92322.0,146617.571429,-0.74
34,2026-02-19,98.64,99.32,95.75,97.32,40699.0,141884.857143,-1.32
35,2026-01-22,103.28,106.28,102.27,105.21,84080.0,65324.857143,1.93
36,2026-02-23,97.22,100.49,96.23,99.35,98483.0,73191.000000,2.13
37,2026-02-24,93.89,95.72,92.27,94.85,40190.0,68758.714286,0.96
38,2026-02-25,91.70,92.28,89.47,90.94,50492.0,70214.571429,-0.76
39,2026-02-26,92.26,95.27,90.49,93.59,90132.0,70914.000000,1.33
40,2026-02-27,93.79,96.14,92.30,94.28,75743.0,68545.571429,0.49
41,2026-03-02,94.30,97.07,92.95,96.54,850000.0,184160.000000,2.24
42,2026-03-03,94.29,95.81,92.55,93.19,90336.0,185053.714286,-1.10
43,2026-03-04,93.95,94.90,92.54,93.59,92479.0,184196.000000,-0.36
45,2026-03-06,90.39,91.24,86.89,87.76,97471.0,192379.000000,-2.63
46,2026-03-09,89.76,92.53,87.80,90.65,66641.0,194686.000000,0.89
47,2026-02-06,98.04,100.96,97.53,99.98,72635.0,192186.428571,1.94
48,2026-03-11,92.68,95.36,90.84,92.99,72745.0,191758.142857,0.31
49,2026-03-12,89.71,90.49,88.09,89.54,95006.0,83901.857143,-0.17

In [27]:
df["Daily_Return"]=((df["Close"]-df["Open"]))/df["Open"]*100
df

C:\Users\HP\AppData\Local\Temp\ipykernel_18856\2707061589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Daily_Return"]=((df["Close"]-df["Open"]))/df["Open"]*100

,Date,Open,High,Low,Close,Volume,Volume_MA_7,Price_Delta,Daily_Return
0,2026-01-02,101.09,103.37,100.08,102.04,89377.0,NaN,0.95,0.939757
1,2026-01-05,101.05,101.99,99.91,100.58,88404.0,NaN,-0.47,-0.465116
2,2026-01-06,102.41,103.15,99.47,101.36,94045.0,NaN,-1.05,-1.025290
3,2026-01-07,105.35,108.05,103.53,106.87,72352.0,NaN,1.52,1.442810
4,2026-01-08,105.13,109.88,104.24,107.49,79790.0,NaN,2.36,2.244840
5,2026-01-09,104.91,108.22,103.42,107.07,81919.0,NaN,2.16,2.058908
6,2026-01-12,107.95,109.49,104.84,106.57,45600.0,78783.857143,-1.38,-1.278370
8,2026-01-14,108.89,111.08,107.60,109.85,67643.0,75679.000000,0.96,0.881624
9,2026-01-15,110.07,114.76,109.21,112.32,80764.0,74587.571429,2.25,2.044154
10,2026-01-16,109.43,111.85,108.13,108.77,49007.0,68153.571429,-0.66,-0.603125
11,2026-01-19,108.79,109.79,106.87,108.72,450000.0,122103.285714,-0.07,-0.064344
12,2026-01-20,109.43,110.92,105.67,107.52,96835.0,124538.285714,-1.91,-1.745408
13,2026-01-21,106.18,107.28,102.64,104.09,77410.0,123894.142857,-2.09,-1.968356
14,2026-01-22,103.28,106.28,102.27,105.21,84080.0,129391.285714,1.93,1.868706
15,2026-01-23,102.47,106.05,101.45,105.48,80447.0,131220.428571,3.01,2.937445
16,2026-01-26,100.84,102.72,99.25,101.00,48208.0,126569.571429,0.16,0.158667
17,2026-01-27,101.61,105.43,99.76,103.92,96491.0,133353.000000,2.31,2.273398
19,2026-01-29,97.83,98.89,95.17,96.84,58589.0,77437.142857,-0.99,-1.011960
20,2026-01-09,104.91,108.22,103.42,107.07,81919.0,75306.285714,2.16,2.058908
21,2026-02-02,100.47,104.83,99.84,103.85,57453.0,72455.285714,3.38,3.364188
22,2026-02-03,100.79,101.81,100.05,101.02,76212.0,71331.285714,0.23,0.228197
23,2026-02-04,98.42,103.33,96.57,101.85,83525.0,71771.000000,3.43,3.485064
24,2026-02-05,97.64,100.11,91.29,92.70,87202.0,77341.571429,-4.94,-5.059402
25,2026-02-06,98.04,100.96,97.53,99.98,72635.0,73933.571429,1.94,1.978784
26,2026-02-09,96.17,98.48,95.52,96.64,73828.0,76110.571429,0.47,0.488718
27,2026-02-10,97.05,99.07,95.25,96.75,620000.0,152979.285714,-0.30,-0.309119
28,2026-02-11,96.17,97.63,95.66,96.65,43420.0,150974.571429,0.48,0.499116
29,2026-02-12,95.84,97.80,91.42,92.16,71216.0,150260.857143,-3.68,-3.839733
30,2026-02-13,94.96,96.20,93.50,94.82,40301.0,144086.000000,-0.14,-0.147430
31,2026-02-16,98.49,101.26,96.95,99.50,85236.0,143805.142857,1.01,1.025485
33,2026-02-18,96.96,98.53,95.38,96.22,92322.0,146617.571429,-0.74,-0.763201
34,2026-02-19,98.64,99.32,95.75,97.32,40699.0,141884.857143,-1.32,-1.338200
35,2026-01-22,103.28,106.28,102.27,105.21,84080.0,65324.857143,1.93,1.868706
36,2026-02-23,97.22,100.49,96.23,99.35,98483.0,73191.000000,2.13,2.190907
37,2026-02-24,93.89,95.72,92.27,94.85,40190.0,68758.714286,0.96,1.022473
38,2026-02-25,91.70,92.28,89.47,90.94,50492.0,70214.571429,-0.76,-0.828790
39,2026-02-26,92.26,95.27,90.49,93.59,90132.0,70914.000000,1.33,1.441578
40,2026-02-27,93.79,96.14,92.30,94.28,75743.0,68545.571429,0.49,0.522444
41,2026-03-02,94.30,97.07,92.95,96.54,850000.0,184160.000000,2.24,2.375398
42,2026-03-03,94.29,95.81,92.55,93.19,90336.0,185053.714286,-1.10,-1.166614
43,2026-03-04,93.95,94.90,92.54,93.59,92479.0,184196.000000,-0.36,-0.383183
45,2026-03-06,90.39,91.24,86.89,87.76,97471.0,192379.000000,-2.63,-2.909614
46,2026-03-09,89.76,92.53,87.80,90.65,66641.0,194686.000000,0.89,0.991533
47,2026-02-06,98.04,100.96,97.53,99.98,72635.0,192186.428571,1.94,1.978784
48,2026-03-11,92.68,95.36,90.84,92.99,72745.0,191758.142857,0.31,0.334484
49,2026-03-12,89.71,90.49,88.09,89.54,95006.0,83901.857143,-0.17,-0.189499

In [28]:
df["Volume"].mean()

np.float64(111812.21739130435)

In [29]:
df["Volume"].max()

850000.0

In [30]:
df["Volume_MA_7"]=df["Volume"].rolling(7).mean() #moving average of volume
df

C:\Users\HP\AppData\Local\Temp\ipykernel_18856\2013728806.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Volume_MA_7"]=df["Volume"].rolling(7).mean() #moving average of volume

,Date,Open,High,Low,Close,Volume,Volume_MA_7,Price_Delta,Daily_Return
0,2026-01-02,101.09,103.37,100.08,102.04,89377.0,NaN,0.95,0.939757
1,2026-01-05,101.05,101.99,99.91,100.58,88404.0,NaN,-0.47,-0.465116
2,2026-01-06,102.41,103.15,99.47,101.36,94045.0,NaN,-1.05,-1.025290
3,2026-01-07,105.35,108.05,103.53,106.87,72352.0,NaN,1.52,1.442810
4,2026-01-08,105.13,109.88,104.24,107.49,79790.0,NaN,2.36,2.244840
5,2026-01-09,104.91,108.22,103.42,107.07,81919.0,NaN,2.16,2.058908
6,2026-01-12,107.95,109.49,104.84,106.57,45600.0,78783.857143,-1.38,-1.278370
8,2026-01-14,108.89,111.08,107.60,109.85,67643.0,75679.000000,0.96,0.881624
9,2026-01-15,110.07,114.76,109.21,112.32,80764.0,74587.571429,2.25,2.044154
10,2026-01-16,109.43,111.85,108.13,108.77,49007.0,68153.571429,-0.66,-0.603125
11,2026-01-19,108.79,109.79,106.87,108.72,450000.0,122103.285714,-0.07,-0.064344
12,2026-01-20,109.43,110.92,105.67,107.52,96835.0,124538.285714,-1.91,-1.745408
13,2026-01-21,106.18,107.28,102.64,104.09,77410.0,123894.142857,-2.09,-1.968356
14,2026-01-22,103.28,106.28,102.27,105.21,84080.0,129391.285714,1.93,1.868706
15,2026-01-23,102.47,106.05,101.45,105.48,80447.0,131220.428571,3.01,2.937445
16,2026-01-26,100.84,102.72,99.25,101.00,48208.0,126569.571429,0.16,0.158667
17,2026-01-27,101.61,105.43,99.76,103.92,96491.0,133353.000000,2.31,2.273398
19,2026-01-29,97.83,98.89,95.17,96.84,58589.0,77437.142857,-0.99,-1.011960
20,2026-01-09,104.91,108.22,103.42,107.07,81919.0,75306.285714,2.16,2.058908
21,2026-02-02,100.47,104.83,99.84,103.85,57453.0,72455.285714,3.38,3.364188
22,2026-02-03,100.79,101.81,100.05,101.02,76212.0,71331.285714,0.23,0.228197
23,2026-02-04,98.42,103.33,96.57,101.85,83525.0,71771.000000,3.43,3.485064
24,2026-02-05,97.64,100.11,91.29,92.70,87202.0,77341.571429,-4.94,-5.059402
25,2026-02-06,98.04,100.96,97.53,99.98,72635.0,73933.571429,1.94,1.978784
26,2026-02-09,96.17,98.48,95.52,96.64,73828.0,76110.571429,0.47,0.488718
27,2026-02-10,97.05,99.07,95.25,96.75,620000.0,152979.285714,-0.30,-0.309119
28,2026-02-11,96.17,97.63,95.66,96.65,43420.0,150974.571429,0.48,0.499116
29,2026-02-12,95.84,97.80,91.42,92.16,71216.0,150260.857143,-3.68,-3.839733
30,2026-02-13,94.96,96.20,93.50,94.82,40301.0,144086.000000,-0.14,-0.147430
31,2026-02-16,98.49,101.26,96.95,99.50,85236.0,143805.142857,1.01,1.025485
33,2026-02-18,96.96,98.53,95.38,96.22,92322.0,146617.571429,-0.74,-0.763201
34,2026-02-19,98.64,99.32,95.75,97.32,40699.0,141884.857143,-1.32,-1.338200
35,2026-01-22,103.28,106.28,102.27,105.21,84080.0,65324.857143,1.93,1.868706
36,2026-02-23,97.22,100.49,96.23,99.35,98483.0,73191.000000,2.13,2.190907
37,2026-02-24,93.89,95.72,92.27,94.85,40190.0,68758.714286,0.96,1.022473
38,2026-02-25,91.70,92.28,89.47,90.94,50492.0,70214.571429,-0.76,-0.828790
39,2026-02-26,92.26,95.27,90.49,93.59,90132.0,70914.000000,1.33,1.441578
40,2026-02-27,93.79,96.14,92.30,94.28,75743.0,68545.571429,0.49,0.522444
41,2026-03-02,94.30,97.07,92.95,96.54,850000.0,184160.000000,2.24,2.375398
42,2026-03-03,94.29,95.81,92.55,93.19,90336.0,185053.714286,-1.10,-1.166614
43,2026-03-04,93.95,94.90,92.54,93.59,92479.0,184196.000000,-0.36,-0.383183
45,2026-03-06,90.39,91.24,86.89,87.76,97471.0,192379.000000,-2.63,-2.909614
46,2026-03-09,89.76,92.53,87.80,90.65,66641.0,194686.000000,0.89,0.991533
47,2026-02-06,98.04,100.96,97.53,99.98,72635.0,192186.428571,1.94,1.978784
48,2026-03-11,92.68,95.36,90.84,92.99,72745.0,191758.142857,0.31,0.334484
49,2026-03-12,89.71,90.49,88.09,89.54,95006.0,83901.857143,-0.17,-0.189499

In [31]:
Volume_mean=df["Volume"].mean()#identifying anomolies

In [32]:
Volume_mean

np.float64(111812.21739130435)

In [33]:
Volume_std=df["Volume"].std()

In [34]:
Volume_std

148250.65636907922

In [35]:
Volume_threshold=Volume_mean+(2*Volume_std)
Volume_threshold

np.float64(408313.53012946283)

In [36]:
anomalies=df[df["Volume"]>Volume_threshold]
anomalies

,Date,Open,High,Low,Close,Volume,Volume_MA_7,Price_Delta,Daily_Return
11,2026-01-19,108.79,109.79,106.87,108.72,450000.0,122103.285714,-0.07,-0.064344
27,2026-02-10,97.05,99.07,95.25,96.75,620000.0,152979.285714,-0.30,-0.309119
41,2026-03-02,94.30,97.07,92.95,96.54,850000.0,184160.000000,2.24,2.375398

In [38]:
#analyse stock return distribution
mean_return=df["Daily_Return"].mean()
print("Mean Return:",mean_return)

variance_return=df["Daily_Return"].var()
print("var return:",variance_return)

std_return=df["Daily_Return"].std()
print("std return:",std_return)

Mean Return: 0.38278962675118444
var return: 3.29038359557356
std return: 1.813941453182423